server:
  port: 8080
spring:
  application:
    name: app1
  datasource:
    output:
      ansi:
        enabled: always
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/ # 템플릿 파일 경로
