server:
  port: 8080
spring:
  application:
    name: app1
  profiles:
    active: dev
  datasource:
    output:
      ansi:
        enabled: always
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/app1?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: sbsst
    password: sbsst123414
  jpa:
    hibernate:
      ddl-auto: update # DB 테이블 자동생성
    show-sql: true # SQL 출력
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/ # 템플릿 파일 경로

